//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Tutorial.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_Tutorial_MyFirstLibrary_ImpulseSender::WritePulse___VOID__BOOLEAN__I4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MyFirstLibrary =
{
    "MyFirstLibrary", 
    0x312F8160,
    method_lookup
};

