version: 1.0.{build}
image: Previous Visual Studio 2013
install:
- ps: >-
    # Start-FileDownload "https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-win32.zip"
    
    Start-FileDownload "https://launchpad.net/gcc-arm-embedded/4.9/4.9-2014-q4-major/+download/gcc-arm-none-eabi-4_9-2014q4-20141203-win32.zip"
    
    Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
    
    .\appveyor\install.ps1
    
build_script:
- cmd: >-
    setenv_gcc 4.9.3 C:\projects\gcc-arm-none-eabi-4_9
    
    cd Solutions\ToppersHRP2onEV3
    
    MSbuild dotnetmf.proj /t:rebuild /p:flavor=release;memory=flash
    
    cd ..\..
    
    cd DeviceCode\Targets\OS\Toppers\hrp2\workspace\helloev3onnetmf
    
    MSbuild dotnetmf.proj /t:rebuild /p:flavor=release;memory=flash
    

artifacts:
- path: BuildOutput\ARM\GCC4.9\le\FLASH\release\ToppersHRP2onEV3\obj\DeviceCode\Targets\OS\Toppers\hrp2\workspace\helloev3onnetmf\hrp2
  name: Release


