//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _TUTORIAL_H_
#define _TUTORIAL_H_

#include <TinyCLR_Interop.h>
struct Library_Tutorial_MyFirstLibrary_ImpulseSender
{
    static const int FIELD___pin = 1;

    TINYCLR_NATIVE_DECLARE(WritePulse___VOID__BOOLEAN__I4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MyFirstLibrary;

#endif  //_TUTORIAL_H_
